### ISSUE TITLE
Licence must be applied correctly

### ISSUE THREAD

**Issue by MaBeuLux88** [mongodb-developer/mongodb-express-rest-api-example#3]
![image](https://user-images.githubusercontent.com/7153911/129749072-f401ac78-15f5-45ac-91b6-b3197a503449.png)

**Comment by Pash10g** [comment]
@MaBeuLux88 This was amended as part of a tech review [PR](https://github.com/mongodb-developer/mongodb-express-rest-api-example/pull/2) by @sis0k0 ... Thanks
